SELECT FLAVOR
FROM (
    SELECT A.FLAVOR, SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY AS A
        INNER JOIN FIRST_HALF AS B
        ON A.FLAVOR = B.FLAVOR
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
    LIMIT 3
) AS subquery;